<a href="https://colab.research.google.com/github/ahsiulkarim/Programming/blob/main/Introduction_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First Problem

print string like hello world and whatever you want


In [ ]:
print("Hello World")

Hello World


In [ ]:
import sys
print(sys.version)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]


In [ ]:
if 8 % 4 == 0:
      print("True")
else:
  print("False")

True


In [ ]:
if 8>2:
  print("Yes 8 is greater than 2")

Yes 8 is greater than 2


In [ ]:
x = 2
x = float(x)
y = "This is our first class"
print(x)
print(y)
print(type(x))
print(type(y))


2.0
This is our first class
<class 'float'>
<class 'str'>


In [ ]:
a,b,c = 32,65,22
print(a + b + c)

119


In [ ]:
def even_odd(num):
  if num % 2 == 0:
    print("Even")
  else:
    print("Odd")

In [ ]:
even_odd(9)

Odd


In [ ]:
a = [2,3,5]
b = [4,5,6]
c = a + b
print(c)

[2, 3, 5, 4, 5, 6]


In [ ]:
x = ["Bangla","English","Math"]
print(x[0])

Bangla


In [ ]:
y = range(9)
print(y)

range(0, 9)


In [ ]:
x = True
y = False
print(x)
print(type(x))

True
<class 'bool'>


In [ ]:
import random
print(random.randint(1,10))

5


In [ ]:
x = ["a","b","c","d"]
k = 4


for i in reversed(range(k)): # 4 0
  print(x[i])

d
c
b
a


In [ ]:
x = "Math"
     #0 1 2 3
print(x[2:])

th


In [ ]:
a = 7
b = 2
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a//b)
print(a**b)
a = 9

9
5
14
3.5
1
3
49


In [ ]:
print(5 + 3 - 2 + 4)

10


In [ ]:
x = [1,2,3,3,5,6,7]
print(x)
x.insert(3,8)
print(x)

[1, 2, 3, 3, 5, 6, 7]
[1, 2, 3, 8, 3, 5, 6, 7]


In [ ]:
x = [1,2,3,4,5,6]

In [ ]:
#example of dictionary

x = {100: 'a', 101: 'b', 103: 'c'}
print(x)
student = {'Audri': 'Undergraduate Student', 'Jannat':'Graduate Student'}
print(student)


{100: 'a', 101: 'b', 103: 'c'}
{'Audri': 'Undergraduate Student', 'Jannat': 'Graduate Student'}


In [ ]:
student = {'2022-1-60-38': {'name':'Audri','age':28,'CGPA':3.50},
           '2022-1-60-35': {'name':'D','age':28,'CGPA':3.50},
           '2022-1-60-37': {'name':'R','age':28,'CGPA':3.50},
           '2022-1-60-40': {'name':'G','age':28,'CGPA':3.50},
           '2023-1-60-085':{'name':'Jannat','age':20, 'CGPA':3.99}}
print(student)
print(type(student))


{'2022-1-60-38': {'name': 'Audri', 'age': 28, 'CGPA': 3.5}, '2022-1-60-35': {'name': 'D', 'age': 28, 'CGPA': 3.5}, '2022-1-60-37': {'name': 'R', 'age': 28, 'CGPA': 3.5}, '2022-1-60-40': {'name': 'G', 'age': 28, 'CGPA': 3.5}, '2023-1-60-085': {'name': 'Jannat', 'age': 20, 'CGPA': 3.99}}
<class 'dict'>


In [ ]:
for id in student.keys():
  print(f"Student ID: {id}")
  print(f"student details: {student[id].get('age')}")

Student ID: 2022-1-60-38
student details: 28
Student ID: 2022-1-60-35
student details: 28
Student ID: 2022-1-60-37
student details: 28
Student ID: 2022-1-60-40
student details: 28
Student ID: 2023-1-60-085
student details: 20


In [ ]:
student.pop('2022-1-60-38')

{'name': 'Audri', 'age': 28, 'CGPA': 3.5}

In [ ]:
del student['2022-1-60-40']

In [ ]:
for id in student.keys():
  print(f"Student ID: {id}")
  print(f"student details: {student[id].get('age')}")

Student ID: 2022-1-60-35
student details: 28
Student ID: 2022-1-60-37
student details: 28
Student ID: 2023-1-60-085
student details: 20


In [ ]:
i = 6
r = 10
while i<r:
  print(i)
  i+=1



6
7
8
9


In [ ]:
num = list(range(2,101,2))
print(num)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [ ]:
myset = set([1,2,3])
print(myset)

{1, 2, 3}


In [ ]:
print(type(myset))

<class 'set'>


In [ ]:
x = input("Enter your number: ")

Enter your number: 2


In [ ]:
print(x)

2


Today we will see how to creat class and object


In [ ]:
class MyClass:
  x = 5
  y = 6


ob = MyClass()
print(ob.x)
print(ob.y)

5
6


In [ ]:
class person:
  def __init__(self,name,age):
    self.name = name
    self.age = age


ob = person(name="Audri",age = 24)
print(ob.name)
print(ob.age)

Audri
24


In [ ]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}"

ob = Person("Audri",24)
print(ob)

Name: Audri, Age: 24


In [ ]:
class Person:
  def __init__(abc,name,age):
    abc.name = name
    abc.age = age

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}"

ob = Person("Audri",24)
print(ob)

Name: Audri, Age: 24


In [ ]:
class Person:
  pass

In [ ]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}"

x = Person("Audri",24)
print(x)

Name: Audri, Age: 24


In [ ]:
class Student(Person):
  def __init__(self,name,age):
    super().__init__(name,age)
    self.grade = "A+"

  def welcome(self):
    print("Welcome to our class")

  def __str__(self):
    return f"Name: {self.name}, Age: {self.age}, Grade: {self.grade}"


In [ ]:
x = Student("Audri",24)
x.welcome()
print(x)

Welcome to our class
Name: Audri, Age: 24, Grade: A+


In [ ]:
name = ("audri","Shayla","Nabila","Sadia")
myit = iter(name)
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

audri
Shayla
Nabila
Sadia


In [ ]:
name = "Audri"
myit = iter(name)
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

A
u
d
r
i


In [ ]:

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a #2
    self.a += 1
    return x


myiter = MyNumbers()
myit = iter(myiter)# 1 2 3 4 5

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

1
2
3
4
5


In [ ]:
disk = {
    "name": "Audri",
    "Age" : 22,
    "year" : 2024
}

print(len(disk))

3


In [ ]:
class Vehical:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model

  def move(self):
    print("move")


class Car:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model

  def move(self):
    print("drive")

class Boat:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model

  def move(self):
    print("sail")

class Plane:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model

  def move(self):
    print("FLY")

car = Car("Toyota","2021CBC")
boat = Boat("Inra","334")
plane = Plane("dark","747")

for x in (car,boat,plane):
  x.move()




drive
sail
FLY


In [ ]:
class Vehical:
  def __init__(self,brand,model):
    self.brand = brand
    self.model = model

  def move(self):
    print("move")


class Car(Vehical):
  pass


class Boat(Vehical):
  def move(self):
    print("Sail")



class Plane(Vehical):
  def move(self):
    print("FLY")

car = Car("Toyota","2021CBC")
boat = Boat("Inra","334")
plane = Plane("dark","747")

for x in (car,boat,plane):
  x.move()




move
Sail
FLY


In [ ]:
def myFun():
  x = 34
  def myInnerFun():
    print(x)
  myInnerFun()


myFun()

34


In [ ]:
import datetime

x = datetime.datetime.now()
print(x)

2024-06-15 17:40:10.328799


In [ ]:
x = min(5,20,70,89)
print(x)

y = max(3,5,6,7,5,3,2,4,67,4,6,6,7,8)
print(y)

5
67


In [ ]:
import math

x = math.gcd(2,4,5,6,7)
print(x)

1


In [ ]:
import json

x = '{"name":"audri","age":22,"City":"Dhaka","name":"a","age":2,"City":"Borishal"}'

y = json.loads(x)

print(y["age"])

2


In [ ]:
disk = {
    "name": "Audri",
    "Age" : 22,
    "year" : 2024
}

y = json.dumps(disk)
print(y)

{"name": "Audri", "Age": 22, "year": 2024}


In [ ]:
print(type(y))

<class 'str'>


In [ ]:
f = open("Intro.txt","r")
print(f.read())

Audri is good.


Hasan



In [ ]:
f = open("Intro.txt","r")
print(f.readline())

Audri is good.



In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(np.__version__)

1.25.2


In [ ]:
a = np.array(42)
print(a)

42


In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.ndim

1

In [ ]:
a = np.array([[1,2,3],[4,5,6],[5,6,7]])
print(a)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [ ]:
a.ndim

2

In [ ]:
a = np.array([1,3,4,5,6])
print(a[2] + a[3])

9


In [ ]:
arr = np.array([1.1,2.2,3.3])
newarr = arr.astype('i')
print(newarr)

[1 2 3]


In [ ]:
arr = np.array([1,2,3])
for x in arr:
  print(x)


1
2
3


In [ ]:
a = np.array([[1,2,3],[4,5,6],[5,6,7]])
print(a)
for x in a:
  print(x)

[[1 2 3]
 [4 5 6]
 [5 6 7]]
[1 2 3]
[4 5 6]
[5 6 7]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)
arr

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [ ]:
x = int(input())
for i in range(x):
  print(i)

100
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
x = [2,3,4,5,6]
for i in x:
  print(i)

2
3
4
5
6


In [ ]:
x = int(input("How many number you wants to input in the list: "))
s = []
for i in range(x):
  a = int(input())
  s.append(a)




How many number you wants to input in the list: 3
23
24
25


In [ ]:
for i in s:
  print(i)

23
24
25


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[3:6])

[4 5 6]
